# Generated by Django 4.1.13 on 2024-05-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_user_is_staff_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
