# Generated by Django 4.1.13 on 2024-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='print', max_length=100),
            preserve_default=False,
        ),
    ]
