# Generated by Django 4.1.13 on 2024-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_restaurant_email_alter_restaurant_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
