# Generated by Django 4.1.13 on 2024-05-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_restaurant_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
